--------------------------------------------------------
--  파일이 생성됨 - 목요일-2월-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MINI_ORDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MINI_ORDER" 
   (	"ORDERID" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"ORDERDATE" DATE, 
	"TOTALAMOUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MINI_ORDERDETAIL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MINI_ORDERDETAIL" 
   (	"ORDERDETAILID" NUMBER, 
	"ORDERID" NUMBER, 
	"PRODUCTID" NUMBER, 
	"QUANTITY" NUMBER, 
	"SUBTOTAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MINI_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MINI_PRODUCT" 
   (	"PRODUCTID" NUMBER, 
	"PRODUCTNAME" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER, 
	"STOCKQUANTITY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MINI_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MINI_USER" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MINI_ORDER
SET DEFINE OFF;
Insert into SYSTEM.MINI_ORDER (ORDERID,USERID,ORDERDATE,TOTALAMOUNT) values (101,'user001',to_date('22/01/30','RR/MM/DD'),1150000);
Insert into SYSTEM.MINI_ORDER (ORDERID,USERID,ORDERDATE,TOTALAMOUNT) values (102,'user001',to_date('22/01/31','RR/MM/DD'),170000);
REM INSERTING into SYSTEM.MINI_ORDERDETAIL
SET DEFINE OFF;
Insert into SYSTEM.MINI_ORDERDETAIL (ORDERDETAILID,ORDERID,PRODUCTID,QUANTITY,SUBTOTAL) values (1,101,1,2,2000000);
Insert into SYSTEM.MINI_ORDERDETAIL (ORDERDETAILID,ORDERID,PRODUCTID,QUANTITY,SUBTOTAL) values (2,101,2,1,150000);
Insert into SYSTEM.MINI_ORDERDETAIL (ORDERDETAILID,ORDERID,PRODUCTID,QUANTITY,SUBTOTAL) values (3,102,3,5,100000);
REM INSERTING into SYSTEM.MINI_PRODUCT
SET DEFINE OFF;
Insert into SYSTEM.MINI_PRODUCT (PRODUCTID,PRODUCTNAME,PRICE,STOCKQUANTITY) values (1,'Treadmill',1000000,50);
Insert into SYSTEM.MINI_PRODUCT (PRODUCTID,PRODUCTNAME,PRICE,STOCKQUANTITY) values (2,'Dumbbell Set',150000,100);
Insert into SYSTEM.MINI_PRODUCT (PRODUCTID,PRODUCTNAME,PRICE,STOCKQUANTITY) values (3,'Yoga Mat',20000,200);
REM INSERTING into SYSTEM.MINI_USER
SET DEFINE OFF;
Insert into SYSTEM.MINI_USER (USERID,USERNAME,PASSWORD,EMAIL,ADDRESS,PHONE,STATUS) values ('user001','John Doe','password123','john@example.com','서울시 강남구 강남대로 123','010-1234-5678','U');
Insert into SYSTEM.MINI_USER (USERID,USERNAME,PASSWORD,EMAIL,ADDRESS,PHONE,STATUS) values ('admin','admin','admin','admin@gmail.com',null,null,'A');
Insert into SYSTEM.MINI_USER (USERID,USERNAME,PASSWORD,EMAIL,ADDRESS,PHONE,STATUS) values ('user002','hong','123456qwer@@','ljs1990.tj@gmail.com','&#44221;&#44592; &#49457;&#45224;&#49884; &#48516;&#45817;&#44396; &#54032;&#44368;&#50669;&#47196;2&#48264;&#44600; 1101&#54840;','010-2222-2222','U');
--------------------------------------------------------
--  DDL for Index SYS_C007547
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007547" ON "SYSTEM"."MINI_ORDER" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007551
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007551" ON "SYSTEM"."MINI_ORDERDETAIL" ("ORDERDETAILID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007533
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007533" ON "SYSTEM"."MINI_PRODUCT" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007544
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007544" ON "SYSTEM"."MINI_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MINI_ORDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_ORDER" MODIFY ("ORDERDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_ORDER" MODIFY ("TOTALAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_ORDER" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MINI_ORDERDETAIL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_ORDERDETAIL" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_ORDERDETAIL" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_ORDERDETAIL" ADD PRIMARY KEY ("ORDERDETAILID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MINI_PRODUCT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_PRODUCT" MODIFY ("PRODUCTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_PRODUCT" MODIFY ("STOCKQUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_PRODUCT" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MINI_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MINI_USER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MINI_USER" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MINI_ORDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_ORDER" ADD FOREIGN KEY ("USERID")
	  REFERENCES "SYSTEM"."MINI_USER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MINI_ORDERDETAIL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MINI_ORDERDETAIL" ADD FOREIGN KEY ("ORDERID")
	  REFERENCES "SYSTEM"."MINI_ORDER" ("ORDERID") ENABLE;
  ALTER TABLE "SYSTEM"."MINI_ORDERDETAIL" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "SYSTEM"."MINI_PRODUCT" ("PRODUCTID") ENABLE;
